site_name: XM Zheng's Blog
site_url: https://xmzheng.cn/
copyright: Copyright &copy; 2025 XM Zheng

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.integrate

plugins:
  - blog:
      blog_dir: .
      post_url_format: "posts/{slug}"
      pagination: true
      pagination_per_page: 5
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
  - meta
  - search
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences