site_name: XM Zheng's Blog
site_url: https://xmzheng.cn/
copyright: Copyright &copy; 2025 XM Zheng

theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans
    code: Noto Sans Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      plain: ""
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.integrate

plugins:
  - blog:
      blog_dir: .
      pagination: true
      pagination_per_page: 5
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
      post_url_format: "posts/{slug}"
  - meta
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans SC

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.details
  - pymdownx.details
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js