name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - run: uv sync --locked
      - run: uv run mkdocs build --clean
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: site
          folder: site
